### ISSUE TITLE
Detect if calc is needed and add it to style value

### ISSUE THREAD

**Issue by tenphi** [tenphi/nude#15]
We can detect syntax that requires `calc` usage. It will greatly simplify declarations. For example:

```html
<nu-block width="100vw - 2br"></nu-block>
```

generated css:
```css
nu-block[width="100vw - 2p"] {
  width: calc(100vw - (var(--nu-padding) * 2));
}
```
